// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/mattruiters/nova/baml_client/stream_types"
)

type parse_stream struct{}

var ParseStream = &parse_stream{}

// / Parse version of ExecuteTask (Takes in string and returns stream_types.WorkerResult)
func (*parse_stream) ExecuteTask(text string, opts ...CallOptionFunc) (stream_types.WorkerResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ExecuteTask: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "ExecuteTask", encoded)
	if err != nil {
		return stream_types.WorkerResult{}, err
	}

	casted := (result).(stream_types.WorkerResult)

	return casted, nil
}

// / Parse version of FixTask (Takes in string and returns stream_types.WorkerResult)
func (*parse_stream) FixTask(text string, opts ...CallOptionFunc) (stream_types.WorkerResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: FixTask: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "FixTask", encoded)
	if err != nil {
		return stream_types.WorkerResult{}, err
	}

	casted := (result).(stream_types.WorkerResult)

	return casted, nil
}

// / Parse version of PlanTask (Takes in string and returns stream_types.PlannerDecision)
func (*parse_stream) PlanTask(text string, opts ...CallOptionFunc) (stream_types.PlannerDecision, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: PlanTask: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "PlanTask", encoded)
	if err != nil {
		return stream_types.PlannerDecision{}, err
	}

	casted := (result).(stream_types.PlannerDecision)

	return casted, nil
}

// / Parse version of RouteEscalation (Takes in string and returns stream_types.EscalationDecision)
func (*parse_stream) RouteEscalation(text string, opts ...CallOptionFunc) (stream_types.EscalationDecision, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: RouteEscalation: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "RouteEscalation", encoded)
	if err != nil {
		return stream_types.EscalationDecision{}, err
	}

	casted := (result).(stream_types.EscalationDecision)

	return casted, nil
}

// / Parse version of ValidateTask (Takes in string and returns stream_types.ValidationResult)
func (*parse_stream) ValidateTask(text string, opts ...CallOptionFunc) (stream_types.ValidationResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ValidateTask: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "ValidateTask", encoded)
	if err != nil {
		return stream_types.ValidationResult{}, err
	}

	casted := (result).(stream_types.ValidationResult)

	return casted, nil
}
