# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "agent.baml": "// Enums for type safety\nenum MessageRole {\n  User \n  Assistant\n}\n\nenum ToolName {\n  AgentTool\n}\n\nenum AgentResponseType {\n  Done\n  ToolCall\n}\n\n// Message structure for conversation history\nclass Message {\n  role MessageRole\n  content string\n}\n\n// Tool call structure with typed tool\nclass ToolCall {\n  tool ToolName\n  args string  // JSON string of arguments\n}\n\nclass AgentToolCall{\n  type \"AgentToolCall\"\n  args string\n}\n\n// Agent response with discriminated union pattern\nclass AgentResponse {\n  type AgentResponseType\n  tool_call ToolCall?\n  message string?\n}\n\n// Main agent loop function\nfunction AgentLoop(\n  messages: Message[],\n  working_dir: string\n) -> AgentResponse {\n  client GPT4o\n\n  prompt #\"\n    You are an AI coding agent helping developers accomplish tasks.\n\n    Working directory: {{ working_dir }}\n\n    Available tools:\n    - AgentTool(message: str) - Proxy to claude CLI to execute arbitrary tasks\n      Sends message to 'claude -p <message>' and returns output.\n      Use this tool to delegate any task to claude CLI.\n\n    RULES:\n    1. Execute ONE tool at a time (no parallel execution)\n    2. After using a tool, wait for the result before deciding next action\n    3. When task is complete, use type=\"Done\" with your message\n    4. Use AgentTool to delegate complex tasks to claude CLI\n\n\n    What do you want to do next? Think step by step.\n\n\n    {{ ctx.output_format(prefix=\"Answer with the following format (execute ONE tool at a time):\\n\") }}\n\n    {% for message in messages %}\n    {{ message.role }}\n    {{ message.content }}\n    {% endfor %}\n  \"#\n\n}\n",
    "clients.baml": "// Learn more about clients at https://docs.boundaryml.com/docs/snippets/clients/overview\n\n// OpenAI client for agent loop\nclient<llm> GPT4o {\n  provider openai\n  options {\n    model \"gpt-5-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n",
    "generators.baml": "// This helps auto-generate libraries you can use in the language of your choice.\ngenerator target {\n    // Python/Pydantic for this project\n    output_type \"python/pydantic\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    // BAML will create a baml_client/ subdirectory within this path\n    output_dir \"../agent_loop_server\"\n    version \"0.218.1\"\n    default_client_mode async\n   \n}\n",
}

def get_baml_files():
    return _file_map