# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentLoop(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AgentLoop", llm_response=llm_response, mode="request")
        return typing.cast(types.AgentResponse, __result__)

    def GenerateMermaidDiagrams(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DiagramSet:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateMermaidDiagrams", llm_response=llm_response, mode="request")
        return typing.cast(types.DiagramSet, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentLoop(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AgentResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AgentLoop", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AgentResponse, __result__)

    def GenerateMermaidDiagrams(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DiagramSet:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateMermaidDiagrams", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DiagramSet, __result__)

    