# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class AgentResponse(BaseModel):
    type: typing.Optional[types.AgentResponseType] = None
    tool_call: typing.Optional["ToolCall"] = None
    message: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Optional[types.MessageRole] = None
    content: typing.Optional[str] = None

class ToolCall(BaseModel):
    tool: typing.Optional[types.ToolName] = None
    args: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
