# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.AgentToolCall": types.AgentToolCall,
    "stream_types.AgentToolCall": stream_types.AgentToolCall,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.ToolCall": types.ToolCall,
    "stream_types.ToolCall": stream_types.ToolCall,


    "types.AgentResponseType": types.AgentResponseType,

    "types.MessageRole": types.MessageRole,

    "types.ToolName": types.ToolName,

}