# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class AgentResponseType(str, Enum):
    Reply = "Reply"
    ToolCall = "ToolCall"

class MessageRole(str, Enum):
    User = "User"
    Assistant = "Assistant"

class ToolName(str, Enum):
    AgentTool = "AgentTool"

# #########################################################################
# Generated classes (3)
# #########################################################################

class AgentResponse(BaseModel):
    type: AgentResponseType
    tool_call: typing.Optional["ToolCall"] = None
    message: typing.Optional[str] = None

class Message(BaseModel):
    role: MessageRole
    content: str

class ToolCall(BaseModel):
    tool: ToolName
    args: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
