// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type EscalationActionEnumView struct {
	inner baml.EnumBuilder
}

func (t *EscalationActionEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EscalationActionEnumView) ValueFIX() (EnumValueView, error) {
	return t.inner.Value("FIX")
}

func (t *EscalationActionEnumView) ValueHUMAN() (EnumValueView, error) {
	return t.inner.Value("HUMAN")
}

func (t *EscalationActionEnumView) ValueSKIP() (EnumValueView, error) {
	return t.inner.Value("SKIP")
}

func (t *TypeBuilder) EscalationAction() (*EscalationActionEnumView, error) {
	bld, err := t.inner.Enum("EscalationAction")
	if err != nil {
		return nil, err
	}
	return &EscalationActionEnumView{inner: bld}, nil
}

func (t *EscalationActionEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TaskSizeEnumView struct {
	inner baml.EnumBuilder
}

func (t *TaskSizeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TaskSizeEnumView) ValueXS() (EnumValueView, error) {
	return t.inner.Value("XS")
}

func (t *TaskSizeEnumView) ValueS() (EnumValueView, error) {
	return t.inner.Value("S")
}

func (t *TaskSizeEnumView) ValueM() (EnumValueView, error) {
	return t.inner.Value("M")
}

func (t *TaskSizeEnumView) ValueL() (EnumValueView, error) {
	return t.inner.Value("L")
}

func (t *TaskSizeEnumView) ValueXL() (EnumValueView, error) {
	return t.inner.Value("XL")
}

func (t *TypeBuilder) TaskSize() (*TaskSizeEnumView, error) {
	bld, err := t.inner.Enum("TaskSize")
	if err != nil {
		return nil, err
	}
	return &TaskSizeEnumView{inner: bld}, nil
}

func (t *TaskSizeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
