// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type EscalationDecisionClassView struct {
	inner baml.ClassBuilder
}

func (t *EscalationDecisionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EscalationDecisionClassView) PropertyAction() (ClassPropertyView, error) {
	return t.inner.Property("action")
}

func (t *EscalationDecisionClassView) PropertyReason() (ClassPropertyView, error) {
	return t.inner.Property("reason")
}

func (t *EscalationDecisionClassView) PropertyFixer_prompt() (ClassPropertyView, error) {
	return t.inner.Property("fixer_prompt")
}

func (t *EscalationDecisionClassView) PropertyHuman_question() (ClassPropertyView, error) {
	return t.inner.Property("human_question")
}

func (t *TypeBuilder) EscalationDecision() (*EscalationDecisionClassView, error) {
	bld, err := t.inner.Class("EscalationDecision")
	if err != nil {
		return nil, err
	}
	return &EscalationDecisionClassView{inner: bld}, nil
}

func (t *EscalationDecisionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PlannerDecisionClassView struct {
	inner baml.ClassBuilder
}

func (t *PlannerDecisionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PlannerDecisionClassView) PropertySize() (ClassPropertyView, error) {
	return t.inner.Property("size")
}

func (t *PlannerDecisionClassView) PropertyShould_split() (ClassPropertyView, error) {
	return t.inner.Property("should_split")
}

func (t *PlannerDecisionClassView) PropertySubtasks() (ClassPropertyView, error) {
	return t.inner.Property("subtasks")
}

func (t *PlannerDecisionClassView) PropertyReasoning() (ClassPropertyView, error) {
	return t.inner.Property("reasoning")
}

func (t *TypeBuilder) PlannerDecision() (*PlannerDecisionClassView, error) {
	bld, err := t.inner.Class("PlannerDecision")
	if err != nil {
		return nil, err
	}
	return &PlannerDecisionClassView{inner: bld}, nil
}

func (t *PlannerDecisionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SubtaskDefinitionClassView struct {
	inner baml.ClassBuilder
}

func (t *SubtaskDefinitionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SubtaskDefinitionClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *SubtaskDefinitionClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *SubtaskDefinitionClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *SubtaskDefinitionClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *SubtaskDefinitionClassView) PropertyPriority() (ClassPropertyView, error) {
	return t.inner.Property("priority")
}

func (t *SubtaskDefinitionClassView) PropertyDepends_on() (ClassPropertyView, error) {
	return t.inner.Property("depends_on")
}

func (t *TypeBuilder) SubtaskDefinition() (*SubtaskDefinitionClassView, error) {
	bld, err := t.inner.Class("SubtaskDefinition")
	if err != nil {
		return nil, err
	}
	return &SubtaskDefinitionClassView{inner: bld}, nil
}

func (t *SubtaskDefinitionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TelemetryEntryClassView struct {
	inner baml.ClassBuilder
}

func (t *TelemetryEntryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TelemetryEntryClassView) PropertyTask_id() (ClassPropertyView, error) {
	return t.inner.Property("task_id")
}

func (t *TelemetryEntryClassView) PropertyAttempt_num() (ClassPropertyView, error) {
	return t.inner.Property("attempt_num")
}

func (t *TelemetryEntryClassView) PropertyModel() (ClassPropertyView, error) {
	return t.inner.Property("model")
}

func (t *TelemetryEntryClassView) PropertyTokens_used() (ClassPropertyView, error) {
	return t.inner.Property("tokens_used")
}

func (t *TelemetryEntryClassView) PropertyDuration_ms() (ClassPropertyView, error) {
	return t.inner.Property("duration_ms")
}

func (t *TelemetryEntryClassView) PropertyCost_usd() (ClassPropertyView, error) {
	return t.inner.Property("cost_usd")
}

func (t *TelemetryEntryClassView) PropertySuccess() (ClassPropertyView, error) {
	return t.inner.Property("success")
}

func (t *TelemetryEntryClassView) PropertyError_message() (ClassPropertyView, error) {
	return t.inner.Property("error_message")
}

func (t *TypeBuilder) TelemetryEntry() (*TelemetryEntryClassView, error) {
	bld, err := t.inner.Class("TelemetryEntry")
	if err != nil {
		return nil, err
	}
	return &TelemetryEntryClassView{inner: bld}, nil
}

func (t *TelemetryEntryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ValidationResultClassView struct {
	inner baml.ClassBuilder
}

func (t *ValidationResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ValidationResultClassView) PropertyPassed() (ClassPropertyView, error) {
	return t.inner.Property("passed")
}

func (t *ValidationResultClassView) PropertyMessage() (ClassPropertyView, error) {
	return t.inner.Property("message")
}

func (t *ValidationResultClassView) PropertyFailures() (ClassPropertyView, error) {
	return t.inner.Property("failures")
}

func (t *TypeBuilder) ValidationResult() (*ValidationResultClassView, error) {
	bld, err := t.inner.Class("ValidationResult")
	if err != nil {
		return nil, err
	}
	return &ValidationResultClassView{inner: bld}, nil
}

func (t *ValidationResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type WorkerResultClassView struct {
	inner baml.ClassBuilder
}

func (t *WorkerResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *WorkerResultClassView) PropertySuccess() (ClassPropertyView, error) {
	return t.inner.Property("success")
}

func (t *WorkerResultClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *WorkerResultClassView) PropertyOutput_files() (ClassPropertyView, error) {
	return t.inner.Property("output_files")
}

func (t *WorkerResultClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *WorkerResultClassView) PropertyQuestions() (ClassPropertyView, error) {
	return t.inner.Property("questions")
}

func (t *WorkerResultClassView) PropertyError_message() (ClassPropertyView, error) {
	return t.inner.Property("error_message")
}

func (t *TypeBuilder) WorkerResult() (*WorkerResultClassView, error) {
	bld, err := t.inner.Class("WorkerResult")
	if err != nil {
		return nil, err
	}
	return &WorkerResultClassView{inner: bld}, nil
}

func (t *WorkerResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
