// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Union3KbugOrKfeatureOrKtask struct {
	variant string

	variant_Ktask *string

	variant_Kbug *string

	variant_Kfeature *string
}

func (u *Union3KbugOrKfeatureOrKtask) Decode(holder *cffi.CFFIValueUnionVariant, typeMap baml.TypeMap) {
	valueHolder := holder.Value
	variantName := holder.ValueOptionName
	switch variantName {
	case "string_task":
		u.variant = "Ktask"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Ktask = &value
	case "string_bug":
		u.variant = "Kbug"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kbug = &value
	case "string_feature":
		u.variant = "Kfeature"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kfeature = &value

	default:
		panic(fmt.Sprintf("invalid union variant: %s", variantName))
	}
}

func (u Union3KbugOrKfeatureOrKtask) Encode() (*cffi.HostValue, error) {
	switch u.variant {

	case "Ktask":
		return baml.EncodeValue(*u.variant_Ktask)

	case "Kbug":
		return baml.EncodeValue(*u.variant_Kbug)

	case "Kfeature":
		return baml.EncodeValue(*u.variant_Kfeature)

	case "":
		return nil, fmt.Errorf("invalid union variant: [unset]")
	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u Union3KbugOrKfeatureOrKtask) BamlTypeName() string {
	return "Union3KbugOrKfeatureOrKtask"
}

func (u Union3KbugOrKfeatureOrKtask) MarshalJSON() ([]byte, error) {
	switch u.variant {

	case "Ktask":
		return json.Marshal(u.variant_Ktask)

	case "Kbug":
		return json.Marshal(u.variant_Kbug)

	case "Kfeature":
		return json.Marshal(u.variant_Kfeature)

	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u *Union3KbugOrKfeatureOrKtask) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &u.variant_Ktask)
	if err == nil {
		u.variant = "Ktask"
		return nil
	} else {
		u.variant_Ktask = nil
	}

	err = json.Unmarshal(data, &u.variant_Kbug)
	if err == nil {
		u.variant = "Kbug"
		return nil
	} else {
		u.variant_Kbug = nil
	}

	err = json.Unmarshal(data, &u.variant_Kfeature)
	if err == nil {
		u.variant = "Kfeature"
		return nil
	} else {
		u.variant_Kfeature = nil
	}

	return fmt.Errorf("invalid union variant: %s", string(data))
}

func Union3KbugOrKfeatureOrKtask__NewKtask() Union3KbugOrKfeatureOrKtask {

	var v string = "task"

	return Union3KbugOrKfeatureOrKtask{
		variant:       "Ktask",
		variant_Ktask: &v,
	}
}

func (u *Union3KbugOrKfeatureOrKtask) SetKtask() {

	var v string = "task"

	u.variant = "Ktask"
	u.variant_Ktask = &v

	u.variant_Kbug = nil

	u.variant_Kfeature = nil

}

func (u *Union3KbugOrKfeatureOrKtask) IsKtask() bool {
	return u.variant == "Ktask"
}

func (u *Union3KbugOrKfeatureOrKtask) AsKtask() *string {
	if u.variant != "Ktask" {
		return nil
	}
	return u.variant_Ktask
}

func Union3KbugOrKfeatureOrKtask__NewKbug() Union3KbugOrKfeatureOrKtask {

	var v string = "bug"

	return Union3KbugOrKfeatureOrKtask{
		variant:      "Kbug",
		variant_Kbug: &v,
	}
}

func (u *Union3KbugOrKfeatureOrKtask) SetKbug() {

	var v string = "bug"

	u.variant = "Kbug"
	u.variant_Kbug = &v

	u.variant_Ktask = nil

	u.variant_Kfeature = nil

}

func (u *Union3KbugOrKfeatureOrKtask) IsKbug() bool {
	return u.variant == "Kbug"
}

func (u *Union3KbugOrKfeatureOrKtask) AsKbug() *string {
	if u.variant != "Kbug" {
		return nil
	}
	return u.variant_Kbug
}

func Union3KbugOrKfeatureOrKtask__NewKfeature() Union3KbugOrKfeatureOrKtask {

	var v string = "feature"

	return Union3KbugOrKfeatureOrKtask{
		variant:          "Kfeature",
		variant_Kfeature: &v,
	}
}

func (u *Union3KbugOrKfeatureOrKtask) SetKfeature() {

	var v string = "feature"

	u.variant = "Kfeature"
	u.variant_Kfeature = &v

	u.variant_Ktask = nil

	u.variant_Kbug = nil

}

func (u *Union3KbugOrKfeatureOrKtask) IsKfeature() bool {
	return u.variant == "Kfeature"
}

func (u *Union3KbugOrKfeatureOrKtask) AsKfeature() *string {
	if u.variant != "Kfeature" {
		return nil
	}
	return u.variant_Kfeature
}
