import Anthropic from '@anthropic-ai/sdk';
import type { SessionState } from '../../shared/types';
import {
  SYSTEM_PROMPT,
  buildContextPrompt,
  formatConversationHistory,
  isReadyToGenerate,
} from './prompts/solution-architect';

export class ClaudeClient {
  private client: Anthropic;

  constructor() {
    this.client = new Anthropic();
  }

  async chat(
    session: SessionState,
    userMessage: string
  ): Promise<{
    response: string;
    shouldGenerate: boolean;
  }> {
    const history = formatConversationHistory(session);
    const contextPrompt = buildContextPrompt(session);

    const response = await this.client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 500, // Keep responses short for voice
      system: `${SYSTEM_PROMPT}\n\n${contextPrompt}`,
      messages: [...history, { role: 'user', content: userMessage }],
    });

    const assistantMessage =
      response.content[0].type === 'text' ? response.content[0].text : '';

    return {
      response: assistantMessage,
      shouldGenerate: isReadyToGenerate(session),
    };
  }

  async generateSpec(session: SessionState): Promise<string> {
    const history = formatConversationHistory(session);

    const response = await this.client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4000,
      system: `Based on the conversation, generate a complete solution specification in markdown format.

Include these sections:
# Solution Specification: {title}

## Summary
## User Value
## Scope (Included/Excluded/Future Considerations)
## Success Criteria
## Technical Constraints
## Edge Cases (table format)
## Implementation Diagram (Mermaid flowchart)
## Effort Estimate (XS/S/M/L/XL with reasoning)

End with:
---
Generated by Solution Architect v2
Confidence: HIGH/MEDIUM/LOW`,
      messages: [
        ...history,
        {
          role: 'user',
          content:
            'Please generate the complete solution specification based on our conversation.',
        },
      ],
    });

    return response.content[0].type === 'text' ? response.content[0].text : '';
  }
}
