// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/mattruiters/nova/baml_client/types"
)

func ExecuteTask(ctx context.Context, task_title string, task_description string, context string, attempt_num int64, opts ...CallOptionFunc) (types.WorkerResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"task_title": task_title, "task_description": task_description, "context": context, "attempt_num": attempt_num},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "ExecuteTask", encoded, callOpts.onTick)
		if err != nil {
			return types.WorkerResult{}, err
		}

		if result.Error != nil {
			return types.WorkerResult{}, result.Error
		}

		casted := (result.Data).(types.WorkerResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "ExecuteTask", encoded, callOpts.onTick)
		if err != nil {
			return types.WorkerResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.WorkerResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.WorkerResult), nil
			}
		}

		return types.WorkerResult{}, fmt.Errorf("No data returned from stream")
	}
}

func FixTask(ctx context.Context, task_title string, task_description string, previous_attempt_summary string, fixer_guidance string, opts ...CallOptionFunc) (types.WorkerResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"task_title": task_title, "task_description": task_description, "previous_attempt_summary": previous_attempt_summary, "fixer_guidance": fixer_guidance},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "FixTask", encoded, callOpts.onTick)
		if err != nil {
			return types.WorkerResult{}, err
		}

		if result.Error != nil {
			return types.WorkerResult{}, result.Error
		}

		casted := (result.Data).(types.WorkerResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "FixTask", encoded, callOpts.onTick)
		if err != nil {
			return types.WorkerResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.WorkerResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.WorkerResult), nil
			}
		}

		return types.WorkerResult{}, fmt.Errorf("No data returned from stream")
	}
}

func PlanTask(ctx context.Context, task_title string, task_description string, context string, opts ...CallOptionFunc) (types.PlannerDecision, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"task_title": task_title, "task_description": task_description, "context": context},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "PlanTask", encoded, callOpts.onTick)
		if err != nil {
			return types.PlannerDecision{}, err
		}

		if result.Error != nil {
			return types.PlannerDecision{}, result.Error
		}

		casted := (result.Data).(types.PlannerDecision)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "PlanTask", encoded, callOpts.onTick)
		if err != nil {
			return types.PlannerDecision{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.PlannerDecision{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.PlannerDecision), nil
			}
		}

		return types.PlannerDecision{}, fmt.Errorf("No data returned from stream")
	}
}

func RouteEscalation(ctx context.Context, task_title string, task_description string, failure_history string, last_error string, opts ...CallOptionFunc) (types.EscalationDecision, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"task_title": task_title, "task_description": task_description, "failure_history": failure_history, "last_error": last_error},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "RouteEscalation", encoded, callOpts.onTick)
		if err != nil {
			return types.EscalationDecision{}, err
		}

		if result.Error != nil {
			return types.EscalationDecision{}, result.Error
		}

		casted := (result.Data).(types.EscalationDecision)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "RouteEscalation", encoded, callOpts.onTick)
		if err != nil {
			return types.EscalationDecision{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.EscalationDecision{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.EscalationDecision), nil
			}
		}

		return types.EscalationDecision{}, fmt.Errorf("No data returned from stream")
	}
}

func ValidateTask(ctx context.Context, task_title string, task_description string, worker_summary string, test_output string, opts ...CallOptionFunc) (types.ValidationResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"task_title": task_title, "task_description": task_description, "worker_summary": worker_summary, "test_output": test_output},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "ValidateTask", encoded, callOpts.onTick)
		if err != nil {
			return types.ValidationResult{}, err
		}

		if result.Error != nil {
			return types.ValidationResult{}, result.Error
		}

		casted := (result.Data).(types.ValidationResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "ValidateTask", encoded, callOpts.onTick)
		if err != nil {
			return types.ValidationResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ValidationResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ValidationResult), nil
			}
		}

		return types.ValidationResult{}, fmt.Errorf("No data returned from stream")
	}
}
