###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import List, Optional, Union

from . import types

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class AgentResponse(BaseModel):
    
    
    type: Optional[types.AgentResponseType] = None
    tool_call: Optional["ToolCall"] = None
    message: Optional[str] = None

class Message(BaseModel):
    
    
    role: Optional[types.MessageRole] = None
    content: Optional[str] = None
    tool_call_id: Optional[str] = None
    tool_name: Optional[str] = None

class ToolCall(BaseModel):
    
    
    tool: Optional[types.ToolName] = None
    args: Optional[str] = None
