// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/mattruiters/nova/baml_client/stream_types"
	"github.com/mattruiters/nova/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.EscalationDecision":        reflect.TypeOf(types.EscalationDecision{}),
	"STREAM_TYPES.EscalationDecision": reflect.TypeOf(stream_types.EscalationDecision{}),
	"TYPES.PlannerDecision":           reflect.TypeOf(types.PlannerDecision{}),
	"STREAM_TYPES.PlannerDecision":    reflect.TypeOf(stream_types.PlannerDecision{}),
	"TYPES.SubtaskDefinition":         reflect.TypeOf(types.SubtaskDefinition{}),
	"STREAM_TYPES.SubtaskDefinition":  reflect.TypeOf(stream_types.SubtaskDefinition{}),
	"TYPES.TelemetryEntry":            reflect.TypeOf(types.TelemetryEntry{}),
	"STREAM_TYPES.TelemetryEntry":     reflect.TypeOf(stream_types.TelemetryEntry{}),
	"TYPES.ValidationResult":          reflect.TypeOf(types.ValidationResult{}),
	"STREAM_TYPES.ValidationResult":   reflect.TypeOf(stream_types.ValidationResult{}),
	"TYPES.WorkerResult":              reflect.TypeOf(types.WorkerResult{}),
	"STREAM_TYPES.WorkerResult":       reflect.TypeOf(stream_types.WorkerResult{}),

	"TYPES.EscalationAction": reflect.TypeOf(types.EscalationAction("")),
	"TYPES.TaskSize":         reflect.TypeOf(types.TaskSize("")),

	"TYPES.string_bug__string_feature__string_task": reflect.TypeOf(types.Union3KbugOrKfeatureOrKtask{}),
}
