###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import List, Optional, Union


class AgentResponseType(str, Enum):
    
    ToolCall = "ToolCall"
    Reply = "Reply"

class MessageRole(str, Enum):
    
    User = "User"
    Assistant = "Assistant"
    Tool = "Tool"

class ToolName(str, Enum):
    
    FileRead = "FileRead"
    FileWrite = "FileWrite"
    GitStatus = "GitStatus"
    RunTests = "RunTests"

class AgentResponse(BaseModel):
    
    
    type: "AgentResponseType"
    tool_call: Optional["ToolCall"] = None
    message: Optional[str] = None

class Message(BaseModel):
    
    
    role: "MessageRole"
    content: str
    tool_call_id: Optional[str] = None
    tool_name: Optional[str] = None

class ToolCall(BaseModel):
    
    
    tool: "ToolName"
    args: str
